services:
  python:
    # image: python:3.11
    build: .
    ports:
      - "8050:8050"
    container_name: lecture2

 # named volume
    volumes:
      - dice_simulator:/app/src/

volumes:
  dice_simulator:

